<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1539967252564' stop='1539967306139'>
    <name>Order:</name>
    <title>Order:</title>
    <test-cases>
        <test-case start='1539967252565' status='failed' stop='1539967306136'>
            <name>Place a Delivery Order</name>
            <title>Place a Delivery Order</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Can't connect to WebDriver.
                Error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/tputvmoh/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tputvmoh/Downloads/apache-ant-1.10.1/bin:/Users/tputvmoh/Documents/apache-maven-3.5.0/bin:/Users/tputvmoh/Library/Android/sdk:/Users/tputvmoh/Library/Android/sdk/platform-tools:/Users/tputvmoh/Library/Android/sdk/tools:/Users/tputvmoh/Downloads'".
                
                Please make sure Selenium Server (ChromeDriver or PhantomJS) is running and accessible</message>
                <stack-trace>Error: An unknown server-side error occurred while processing the command. Original error: Unable to launch WebDriverAgent because of xcodebuild failure: "Carthage binary is not found. Install using `brew install carthage` if it is not installed and make sure the root folder, where carthage binary is installed, is present in PATH environment variable. The current PATH value: '/Users/tputvmoh/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/tputvmoh/Downloads/apache-ant-1.10.1/bin:/Users/tputvmoh/Documents/apache-maven-3.5.0/bin:/Users/tputvmoh/Library/Android/sdk:/Users/tputvmoh/Library/Android/sdk/platform-tools:/Users/tputvmoh/Library/Android/sdk/tools:/Users/tputvmoh/Downloads'".
                    at new RuntimeError (/usr/local/lib/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
                    at Request._callback (/usr/local/lib/node_modules/webdriverio/build/lib/utils/RequestHandler.js:316:39)
                    at Request.self.callback (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:185:22)
                    at emitTwo (events.js:126:13)
                    at Request.emit (events.js:214:7)
                    at Request.&lt;anonymous> (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:1161:10)
                    at emitOne (events.js:116:13)
                    at Request.emit (events.js:211:7)
                    at IncomingMessage.&lt;anonymous> (/usr/local/lib/node_modules/webdriverio/node_modules/request/request.js:1083:12)
                    at Object.onceWrapper (events.js:313:30)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>