<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1539867345881' stop='1539867376156'>
    <name>Order:</name>
    <title>Order:</title>
    <test-cases>
        <test-case start='1539867345882' status='failed' stop='1539867362578'>
            <name>Place a Delivery Order</name>
            <title>Place a Delivery Order</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1539867360906' status='failed' stop='1539867362578'>
                    <name>Context: Before </name>
                    <title>Context: Before </title>
                    <attachments/>
                    <steps>
                        <step start='1539867360906' status='passed' stop='1539867362578'>
                            <name>I am on page "/"</name>
                            <title>I am on page "/"</title>
                            <attachments/>
                            <steps/>
                        </step>
                    </steps>
                </step>
            </steps>
            <attachments>
                <attachment title='Last Seen Screenshot' source='88283579-af12-49c9-a1c6-f6cf4acfbcff-attachment.png' type='image/png' size='323862'/>
            </attachments>
            <failure>
                <message>loginPage.clickSignIn is not a function</message>
                <stack-trace>TypeError: loginPage.clickSignIn is not a function
                    at Context.Before (/Users/tputvmoh/Downloads/codecept/end2end/tests/mobileWeb/mobile_collectionOrder_test.js:5:13)
                    at Context.&lt;anonymous> (/usr/local/lib/node_modules/codeceptjs/lib/scenario.js:150:10)
                    at callFnAsync (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:377:21)
                    at Hook.Runnable.run (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:324:7)
                    at next (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:304:10)
                    at /usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:329:7
                    at done (/usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:301:5)
                    at /usr/local/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:359:11
                    at &lt;anonymous>
                    at process._tickDomainCallback (internal/process/next_tick.js:228:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>